/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accenture.utils;

import java.util.HashMap;
import java.util.LinkedHashMap;

/**
 *
 * @author Chethan 
 */
public class MasterTemplateUtil {
    HashMap<String, String> allSegmentMaster = new HashMap<>();
    LinkedHashMap<String, String[]> mshFieldValuePair = new LinkedHashMap<>();
    LinkedHashMap<String, String[]> pidFieldValuePair = new LinkedHashMap<>();
    
    private void setAllSegmentMaster(String value, String key){
        this.allSegmentMaster.put(key, value);
    }
    
    public HashMap getAllSegmentMaster(){
        return this.allSegmentMaster;
    }
    
    public void setMSHFieldValuePair(String key, String min, String max, String description){
        String[] value = {min ,max, description};
        this.mshFieldValuePair.put(key, value);
    }
    
    public LinkedHashMap getMSHFieldValuePair(){
        return this.mshFieldValuePair;
    }
    
    public void setPIDFieldValuePair(String key, String min, String max, String description){
        String[] value = {min ,max, description};
        this.pidFieldValuePair.put(key, value);
    }
    
    public LinkedHashMap getPIDFieldValuePair(){
        return this.pidFieldValuePair;
    }
    
    public void buildMSHSegement(){
        this.setMSHFieldValuePair("MSH-ALL", "" ,"" ,"Entire MSH Segment");
        this.setMSHFieldValuePair("MSH-0", "1" ,"1" ,"Segment ID");
        this.setMSHFieldValuePair("MSH-1", "1" ,"1" ,"Field Separator (ST)");
        this.setMSHFieldValuePair("MSH-2", "1" ,"1" ,"Encoding Characters (ST)");
        this.setMSHFieldValuePair("MSH-3", "0" ,"1" ,"Sending Application");
        this.setMSHFieldValuePair("MSH-3.1", "0" ,"1" ,"Sending Application (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-3.2", "" ,"" ,"Sending Application (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-3.3", "" ,"" ,"Sending Application (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-4", "0" ,"1" ,"Sending Facility (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-4.1", "0" ,"1" ,"Sending Facility (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-4.2", "" ,"" ,"Sending Facility (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-4.3", "" ,"" ,"Sending Facility (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-5", "0" ,"1" ,"Receiving Application");
        this.setMSHFieldValuePair("MSH-5.1", "0" ,"1" ,"Receiving Application (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-5.2", "" ,"" ,"Receiving Application (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-5.3", "" ,"" ,"Receiving Application (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-6", "0" ,"1" ,"Receiving Facility");
        this.setMSHFieldValuePair("MSH-6.1", "0" ,"1" ,"Receiving Facility (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-6.2", "" ,"" ,"Receiving Facility (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-6.3", "" ,"" ,"Receiving Facility (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-7", "1" ,"1" ,"Date/Time of Message (DTM)");
        this.setMSHFieldValuePair("MSH-8", "0" ,"1" ,"Security (ST)");
        this.setMSHFieldValuePair("MSH-9", "1" ,"1" ,"Message Type");
        this.setMSHFieldValuePair("MSH-9.1", "1" ,"1" ,"Message Type (MSG).Message Code (ID)");
        this.setMSHFieldValuePair("MSH-9.2", "" ,"" ,"Message Type (MSG).Trigger Event (ID)");
        this.setMSHFieldValuePair("MSH-9.3", "" ,"" ,"Message Type (MSG).Message Structure (ID)");
        this.setMSHFieldValuePair("MSH-10", "1" ,"1" ,"Message Control ID (ST)");
        this.setMSHFieldValuePair("MSH-11", "1" ,"1" ,"Processing ID");
        this.setMSHFieldValuePair("MSH-11.1", "1" ,"1" ,"Processing ID (PT).Processing ID (ID)");
        this.setMSHFieldValuePair("MSH-11.2", "" ,"" ,"Processing ID (PT).Processing Mode (ID)");
        this.setMSHFieldValuePair("MSH-12", "1" ,"1" ,"Version ID (VID)");
        this.setMSHFieldValuePair("MSH-12.1", "1" ,"1" ,"Version ID (VID).Version ID (ID)");
        this.setMSHFieldValuePair("MSH-12.2", "" ,"" ,"Version ID (VID).Internationalization Code");
        this.setMSHFieldValuePair("MSH-12.2.1", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Identifier (ST)");
        this.setMSHFieldValuePair("MSH-12.2.2", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Text (ST)");
        this.setMSHFieldValuePair("MSH-12.2.3", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Name of Coding System (ID)");
        this.setMSHFieldValuePair("MSH-12.2.4", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Alternate Identifier (ST)");
        this.setMSHFieldValuePair("MSH-12.2.5", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Alternate Text (ST)");
        this.setMSHFieldValuePair("MSH-12.2.6", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Name of Alternate Coding System (ID)");
        this.setMSHFieldValuePair("MSH-12.2.7", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Coding System Version ID (ST)");
        this.setMSHFieldValuePair("MSH-12.2.8", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Alternate Coding System Version ID (ST)");
        this.setMSHFieldValuePair("MSH-12.2.9", "" ,"" ,"Version ID (VID).Internationalization Code (CWE).Original Text (ST)");
        this.setMSHFieldValuePair("MSH-12.3", "" ,"" ,"Version ID (VID).International Version ID");
        this.setMSHFieldValuePair("MSH-12.3.1", "" ,"" ,"Version ID (VID).International Version ID (CWE).Identifier (ST)");
        this.setMSHFieldValuePair("MSH-12.3.2", "" ,"" ,"Version ID (VID).International Version ID (CWE).Text (ST)");
        this.setMSHFieldValuePair("MSH-12.3.3", "" ,"" ,"Version ID (VID).International Version ID (CWE).Name of Coding System (ID)");
        this.setMSHFieldValuePair("MSH-12.3.4", "" ,"" ,"Version ID (VID).International Version ID (CWE).Alternate Identifier (ST)");
        this.setMSHFieldValuePair("MSH-12.3.5", "" ,"" ,"Version ID (VID).International Version ID (CWE).Alternate Text (ST)");
        this.setMSHFieldValuePair("MSH-12.3.6", "" ,"" ,"Version ID (VID).International Version ID (CWE).Name of Alternate Coding System (ID)");
        this.setMSHFieldValuePair("MSH-12.3.7", "" ,"" ,"Version ID (VID).International Version ID (CWE).Coding System Version ID (ST)");
        this.setMSHFieldValuePair("MSH-12.3.8", "" ,"" ,"Version ID (VID).International Version ID (CWE).Alternate Coding System Version ID (ST)");
        this.setMSHFieldValuePair("MSH-12.3.9", "" ,"" ,"Version ID (VID).International Version ID (CWE).Original Text (ST)");
        this.setMSHFieldValuePair("MSH-13", "0" ,"1" ,"Sequence Number (NM)");
        this.setMSHFieldValuePair("MSH-14", "0" ,"1" ,"Continuation Pointer (ST)");
        this.setMSHFieldValuePair("MSH-15", "0" ,"1" ,"Accept Acknowledgment Type (ID)");
        this.setMSHFieldValuePair("MSH-16", "0" ,"1" ,"Application Acknowledgment Type (ID)");
        this.setMSHFieldValuePair("MSH-17", "0" ,"1" ,"Country Code (ID)");
        this.setMSHFieldValuePair("MSH-18", "0" ,"*" ,"Character Set (ID)");
        this.setMSHFieldValuePair("MSH-19", "0" ,"1" ,"Principal Language Of Message");
        this.setMSHFieldValuePair("MSH-19.1", "0" ,"1" ,"Principal Language Of Message (CWE).Identifier (ST)");
        this.setMSHFieldValuePair("MSH-19.2", "" ,"" ,"Principal Language Of Message (CWE).Text (ST)");
        this.setMSHFieldValuePair("MSH-19.3", "" ,"" ,"Principal Language Of Message (CWE).Name of Coding System (ID)");
        this.setMSHFieldValuePair("MSH-19.4", "" ,"" ,"Principal Language Of Message (CWE).Alternate Identifier (ST)");
        this.setMSHFieldValuePair("MSH-19.5", "" ,"" ,"Principal Language Of Message (CWE).Alternate Text (ST)");
        this.setMSHFieldValuePair("MSH-19.6", "" ,"" ,"Principal Language Of Message (CWE).Name of Alternate Coding System (ID)");
        this.setMSHFieldValuePair("MSH-19.7", "" ,"" ,"Principal Language Of Message (CWE).Coding System Version ID (ST)");
        this.setMSHFieldValuePair("MSH-19.8", "" ,"" ,"Principal Language Of Message (CWE).Alternate Coding System Version ID (ST)");
        this.setMSHFieldValuePair("MSH-19.9", "" ,"" ,"Principal Language Of Message (CWE).Original Text (ST)");
        this.setMSHFieldValuePair("MSH-20", "0" ,"1" ,"Alternate Character Set Handling Scheme (ID)");
        this.setMSHFieldValuePair("MSH-21", "0" ,"*" ,"Message Profile Identifier (EI)");
        this.setMSHFieldValuePair("MSH-21.1", "0" ,"*" ,"Message Profile Identifier (EI).Entity Identifier (ST)");
        this.setMSHFieldValuePair("MSH-21.2", "" ,"" ,"Message Profile Identifier (EI).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-21.3", "" ,"" ,"Message Profile Identifier (EI).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-21.4", "" ,"" ,"Message Profile Identifier (EI).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-22", "0" ,"1" ,"Sending Responsible Organization");
        this.setMSHFieldValuePair("MSH-22.1", "0" ,"1" ,"Sending Responsible Organization (XON).Organization Name (ST)");
        this.setMSHFieldValuePair("MSH-22.2", "" ,"" ,"Sending Responsible Organization (XON).Organization Name Type Code (IS)");
        this.setMSHFieldValuePair("MSH-22.3", "" ,"" ,"Sending Responsible Organization (XON).ID Number (NM)");
        this.setMSHFieldValuePair("MSH-22.4", "" ,"" ,"Sending Responsible Organization (XON).Identifier Check Digit (NM)");
        this.setMSHFieldValuePair("MSH-22.5", "" ,"" ,"Sending Responsible Organization (XON).Check Digit Scheme (ID)");
        this.setMSHFieldValuePair("MSH-22.6", "" ,"" ,"Sending Responsible Organization (XON).Assigning Authority");
        this.setMSHFieldValuePair("MSH-22.6.1", "" ,"" ,"Sending Responsible Organization (XON).Assigning Authority (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-22.6.2", "" ,"" ,"Sending Responsible Organization (XON).Assigning Authority (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-22.6.3", "" ,"" ,"Sending Responsible Organization (XON).Assigning Authority (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-22.7", "" ,"" ,"Sending Responsible Organization (XON).Identifier Type Code (ID)");
        this.setMSHFieldValuePair("MSH-22.8", "" ,"" ,"Sending Responsible Organization (XON).Assigning Facility");
        this.setMSHFieldValuePair("MSH-22.8.1", "" ,"" ,"Sending Responsible Organization (XON).Assigning Facility (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-22.8.2", "" ,"" ,"Sending Responsible Organization (XON).Assigning Facility (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-22.8.3", "" ,"" ,"Sending Responsible Organization (XON).Assigning Facility (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-22.9", "" ,"" ,"Sending Responsible Organization (XON).Name Representation Code (ID)");
        this.setMSHFieldValuePair("MSH-22.10", "" ,"" ,"Sending Responsible Organization (XON).Organization Identifier (ST)");
        this.setMSHFieldValuePair("MSH-23", "0" ,"1" ,"Receiving Responsible Organization");
        this.setMSHFieldValuePair("MSH-23.1.1", "0" ,"1" ,"Receiving Responsible Organization (XON).Organization Name (ST)");
        this.setMSHFieldValuePair("MSH-23.2.1", "" ,"" ,"Receiving Responsible Organization (XON).Organization Name Type Code (IS)");
        this.setMSHFieldValuePair("MSH-23.3.1", "" ,"" ,"Receiving Responsible Organization (XON).ID Number (NM)");
        this.setMSHFieldValuePair("MSH-23.4.1", "" ,"" ,"Receiving Responsible Organization (XON).Identifier Check Digit (NM)");
        this.setMSHFieldValuePair("MSH-23.5.1", "" ,"" ,"Receiving Responsible Organization (XON).Check Digit Scheme (ID)");
        this.setMSHFieldValuePair("MSH-23.6", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Authority ");
        this.setMSHFieldValuePair("MSH-23.6.1", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Authority (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-23.6.2", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Authority (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-23.6.3", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Authority (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-23.7.1", "" ,"" ,"Receiving Responsible Organization (XON).Identifier Type Code (ID)");
        this.setMSHFieldValuePair("MSH-23.8", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Facility");
        this.setMSHFieldValuePair("MSH-23.8.1", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Facility (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-23.8.2", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Facility (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-23.8.3", "" ,"" ,"Receiving Responsible Organization (XON).Assigning Facility (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-23.9.1", "" ,"" ,"Receiving Responsible Organization (XON).Name Representation Code (ID)");
        this.setMSHFieldValuePair("MSH-23.10.1", "" ,"" ,"Receiving Responsible Organization (XON).Organization Identifier (ST)");
        this.setMSHFieldValuePair("MSH-24", "0" ,"1" ,"Sending Network Address");
        this.setMSHFieldValuePair("MSH-24.1.1", "0" ,"1" ,"Sending Network Address (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-24.2.1", "" ,"" ,"Sending Network Address (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-24.3.1", "" ,"" ,"Sending Network Address (HD).Universal ID Type (ID)");
        this.setMSHFieldValuePair("MSH-25", "0" ,"1" ,"Receiving Network Address");
        this.setMSHFieldValuePair("MSH-25.1.1", "0" ,"1" ,"Receiving Network Address (HD).Namespace ID (IS)");
        this.setMSHFieldValuePair("MSH-25.2.1", "" ,"" ,"Receiving Network Address (HD).Universal ID (ST)");
        this.setMSHFieldValuePair("MSH-25.3.1", "" ,"" ,"Receiving Network Address (HD).Universal ID Type (ID)");
    }
    
    public void buildEVNSegement(){
    }
    
    public void buildPIDSegement(){
        this.setPIDFieldValuePair("PID-ALL", "" ,"" ,"Entire PID Segment");
        this.setPIDFieldValuePair("PID-0", "1" ,"1" ,"Segment ID");
        this.setPIDFieldValuePair("PID-1", "0" ,"1" ,"Set ID - PID (SI)");
        this.setPIDFieldValuePair("PID-2", "0" ,"1" ,"Patient ID (CX)");
        this.setPIDFieldValuePair("PID-2.1", "0" ,"1" ,"Patient ID (CX).ID Number (ST)");
        this.setPIDFieldValuePair("PID-2.2", "" ,"" ,"Patient ID (CX).Identifier Check Digit (ST)");
        this.setPIDFieldValuePair("PID-2.3", "" ,"" ,"Patient ID (CX).Check Digit Scheme (ID)");
        this.setPIDFieldValuePair("PID-2.4", "" ,"" ,"Patient ID (CX).Assigning Authority (HD");
        this.setPIDFieldValuePair("PID-2.4.1", "" ,"" ,"Patient ID (CX).Assigning Authority (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-2.4.2", "" ,"" ,"Patient ID (CX).Assigning Authority (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-2.4.3", "" ,"" ,"Patient ID (CX).Assigning Authority (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-2.5", "" ,"" ,"Patient ID (CX).Identifier Type Code (ID)");
        this.setPIDFieldValuePair("PID-2.6", "" ,"" ,"Patient ID (CX).Assigning Facility (HD)");
        this.setPIDFieldValuePair("PID-2.6.1", "" ,"" ,"Patient ID (CX).Assigning Facility (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-2.6.2", "" ,"" ,"Patient ID (CX).Assigning Facility (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-2.6.3", "" ,"" ,"Patient ID (CX).Assigning Facility (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-2.7", "" ,"" ,"Patient ID (CX).Effective Date (DT)");
        this.setPIDFieldValuePair("PID-2.8", "" ,"" ,"Patient ID (CX).Expiration Date (DT)");
        this.setPIDFieldValuePair("PID-2.9", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE)");
        this.setPIDFieldValuePair("PID-2.9.1", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-2.9.2", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-2.9.3", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-2.9.4", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-2.9.5", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-2.9.6", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-2.9.7", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-2.9.8", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-2.9.9", "" ,"" ,"Patient ID (CX).Assigning Jurisdiction (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-2.10", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE)");
        this.setPIDFieldValuePair("PID-2.10.1", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-2.10.2", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-2.10.3", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-2.10.4", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-2.10.5", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-2.10.6", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-2.10.7", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-2.10.8", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-2.10.9", "" ,"" ,"Patient ID (CX).Assigning Agency or Department (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-3", "1" ,"*" ,"Patient Identifier List (CX)");
        this.setPIDFieldValuePair("PID-3.1", "1" ,"*" ,"Patient Identifier List (CX).ID Number (ST)");
        this.setPIDFieldValuePair("PID-3.2", "" ,"" ,"Patient Identifier List (CX).Identifier Check Digit (ST)");
        this.setPIDFieldValuePair("PID-3.3", "" ,"" ,"Patient Identifier List (CX).Check Digit Scheme (ID)");
        this.setPIDFieldValuePair("PID-3.4", "" ,"" ,"Patient Identifier List (CX).Assigning Authority (HD)");
        this.setPIDFieldValuePair("PID-3.4.1", "" ,"" ,"Patient Identifier List (CX).Assigning Authority (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-3.4.2", "" ,"" ,"Patient Identifier List (CX).Assigning Authority (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-3.4.3", "" ,"" ,"Patient Identifier List (CX).Assigning Authority (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-3.5", "" ,"" ,"Patient Identifier List (CX).Identifier Type Code (ID)");
        this.setPIDFieldValuePair("PID-3.6", "" ,"" ,"Patient Identifier List (CX).Assigning Facility (HD)");
        this.setPIDFieldValuePair("PID-3.6.1", "" ,"" ,"Patient Identifier List (CX).Assigning Facility (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-3.6.2", "" ,"" ,"Patient Identifier List (CX).Assigning Facility (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-3.6.3", "" ,"" ,"Patient Identifier List (CX).Assigning Facility (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-3.7", "" ,"" ,"Patient Identifier List (CX).Effective Date (DT)");
        this.setPIDFieldValuePair("PID-3.8", "" ,"" ,"Patient Identifier List (CX).Expiration Date (DT)");
        this.setPIDFieldValuePair("PID-3.9", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE)");
        this.setPIDFieldValuePair("PID-3.9.1", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-3.9.2", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-3.9.3", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-3.9.4", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-3.9.5", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-3.9.6", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-3.9.7", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-3.9.8", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-3.9.9", "" ,"" ,"Patient Identifier List (CX).Assigning Jurisdiction (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-3.10", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE)");
        this.setPIDFieldValuePair("PID-3.10.1", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-3.10.2", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-3.10.3", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-3.10.4", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-3.10.5", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-3.10.6", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-3.10.7", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-3.10.8", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-3.10.9", "" ,"" ,"Patient Identifier List (CX).Assigning Agency or Department (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-4", "0" ,"*" ,"Alternate Patient ID - PID (CX)");
        this.setPIDFieldValuePair("PID-4.1", "0" ,"*" ,"Alternate Patient ID - PID (CX).ID Number (ST)");
        this.setPIDFieldValuePair("PID-4.2", "" ,"" ,"Alternate Patient ID - PID (CX).Identifier Check Digit (ST)");
        this.setPIDFieldValuePair("PID-4.3", "" ,"" ,"Alternate Patient ID - PID (CX).Check Digit Scheme (ID)");
        this.setPIDFieldValuePair("PID-4.4", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Authority (HD)");
        this.setPIDFieldValuePair("PID-4.4.1", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Authority (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-4.4.2", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Authority (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-4.4.3", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Authority (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-4.5", "" ,"" ,"Alternate Patient ID - PID (CX).Identifier Type Code (ID)");
        this.setPIDFieldValuePair("PID-4.6", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Facility (HD)");
        this.setPIDFieldValuePair("PID-4.6.1", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Facility (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-4.6.2", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Facility (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-4.6.3", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Facility (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-4.7", "" ,"" ,"Alternate Patient ID - PID (CX).Effective Date (DT)");
        this.setPIDFieldValuePair("PID-4.8", "" ,"" ,"Alternate Patient ID - PID (CX).Expiration Date (DT)");
        this.setPIDFieldValuePair("PID-4.9", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE)");
        this.setPIDFieldValuePair("PID-4.9.1", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-4.9.2", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-4.9.3", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-4.9.4", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-4.9.5", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-4.9.6", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-4.9.7", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-4.9.8", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-4.9.9", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Jurisdiction (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-4.10", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE)");
        this.setPIDFieldValuePair("PID-4.10.1", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-4.10.2", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-4.10.3", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-4.10.4", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-4.10.5", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-4.10.6", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-4.10.7", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-4.10.8", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-4.10.9", "" ,"" ,"Alternate Patient ID - PID (CX).Assigning Agency or Department (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-5", "1" ,"*" ,"Patient Name (XPN)");
        this.setPIDFieldValuePair("PID-5.1", "1" ,"*" ,"Patient Name (XPN).Family Name (FN)");
        this.setPIDFieldValuePair("PID-5.1.1", "1" ,"*" ,"Patient Name (XPN).Family Name (FN).Surname (ST)");
        this.setPIDFieldValuePair("PID-5.1.2", "" ,"" ,"Patient Name (XPN).Family Name (FN).Own Surname Prefix (ST)");
        this.setPIDFieldValuePair("PID-5.1.3", "" ,"" ,"Patient Name (XPN).Family Name (FN).Own Surname (ST)");
        this.setPIDFieldValuePair("PID-5.1.4", "" ,"" ,"Patient Name (XPN).Family Name (FN).Surname Prefix from Partner/Spouse (ST)");
        this.setPIDFieldValuePair("PID-5.1.5", "" ,"" ,"Patient Name (XPN).Family Name (FN).Surname from Partner/Spouse (ST)");
        this.setPIDFieldValuePair("PID-5.2", "" ,"" ,"Patient Name (XPN).Given Name (ST)");
        this.setPIDFieldValuePair("PID-5.3", "" ,"" ,"Patient Name (XPN).Second and Further Given Names or Initials Thereof (ST)");
        this.setPIDFieldValuePair("PID-5.4", "" ,"" ,"Patient Name (XPN).Suffix (e.g., JR or III) (ST)");
        this.setPIDFieldValuePair("PID-5.5", "" ,"" ,"Patient Name (XPN).Prefix (e.g., DR) (ST)");
        this.setPIDFieldValuePair("PID-5.6", "" ,"" ,"Patient Name (XPN).Degree (e.g., MD) (IS)");
        this.setPIDFieldValuePair("PID-5.7", "" ,"" ,"Patient Name (XPN).Name Type Code (ID)");
        this.setPIDFieldValuePair("PID-5.8", "" ,"" ,"Patient Name (XPN).Name Representation Code (ID)");
        this.setPIDFieldValuePair("PID-5.9", "" ,"" ,"Patient Name (XPN).Name Context (CWE)");
        this.setPIDFieldValuePair("PID-5.9.1", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-5.9.2", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-5.9.3", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-5.9.4", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-5.9.5", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-5.9.6", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-5.9.7", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-5.9.8", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-5.9.9", "" ,"" ,"Patient Name (XPN).Name Context (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-5.10", "" ,"" ,"Patient Name (XPN).Name Validity Range (DR)");
        this.setPIDFieldValuePair("PID-5.10.1", "" ,"" ,"Patient Name (XPN).Name Validity Range (DR).Range Start Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-5.10.2", "" ,"" ,"Patient Name (XPN).Name Validity Range (DR).Range End Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-5.11", "" ,"" ,"Patient Name (XPN).Name Assembly Order (ID)");
        this.setPIDFieldValuePair("PID-5.12", "" ,"" ,"Patient Name (XPN).Effective Date (DTM)");
        this.setPIDFieldValuePair("PID-5.13", "" ,"" ,"Patient Name (XPN).Expiration Date (DTM)");
        this.setPIDFieldValuePair("PID-5.14", "" ,"" ,"Patient Name (XPN).Professional Suffix (ST)");
        this.setPIDFieldValuePair("PID-6", "0" ,"*" ,"Mother's Maiden Name (XPN)");
        this.setPIDFieldValuePair("PID-6.1", "0" ,"*" ,"Mother's Maiden Name (XPN).Family Name (FN)");
        this.setPIDFieldValuePair("PID-6.1.1", "0" ,"*" ,"Mother's Maiden Name (XPN).Family Name (FN).Surname (ST)");
        this.setPIDFieldValuePair("PID-6.1.2", "" ,"" ,"Mother's Maiden Name (XPN).Family Name (FN).Own Surname Prefix (ST)");
        this.setPIDFieldValuePair("PID-6.1.3", "" ,"" ,"Mother's Maiden Name (XPN).Family Name (FN).Own Surname (ST)");
        this.setPIDFieldValuePair("PID-6.1.4", "" ,"" ,"Mother's Maiden Name (XPN).Family Name (FN).Surname Prefix from Partner/Spouse (ST)");
        this.setPIDFieldValuePair("PID-6.1.5", "" ,"" ,"Mother's Maiden Name (XPN).Family Name (FN).Surname from Partner/Spouse (ST)");
        this.setPIDFieldValuePair("PID-6.2", "" ,"" ,"Mother's Maiden Name (XPN).Given Name (ST)");
        this.setPIDFieldValuePair("PID-6.3", "" ,"" ,"Mother's Maiden Name (XPN).Second and Further Given Names or Initials Thereof (ST)");
        this.setPIDFieldValuePair("PID-6.4", "" ,"" ,"Mother's Maiden Name (XPN).Suffix (e.g., JR or III) (ST)");
        this.setPIDFieldValuePair("PID-6.5", "" ,"" ,"Mother's Maiden Name (XPN).Prefix (e.g., DR) (ST)");
        this.setPIDFieldValuePair("PID-6.6", "" ,"" ,"Mother's Maiden Name (XPN).Degree (e.g., MD) (IS)");
        this.setPIDFieldValuePair("PID-6.7", "" ,"" ,"Mother's Maiden Name (XPN).Name Type Code (ID)");
        this.setPIDFieldValuePair("PID-6.8", "" ,"" ,"Mother's Maiden Name (XPN).Name Representation Code (ID)");
        this.setPIDFieldValuePair("PID-6.9", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE)");
        this.setPIDFieldValuePair("PID-6.9.1", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-6.9.2", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-6.9.3", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-6.9.4", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-6.9.5", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-6.9.6", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-6.9.7", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-6.9.8", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-6.9.9", "" ,"" ,"Mother's Maiden Name (XPN).Name Context (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-6.10", "" ,"" ,"Mother's Maiden Name (XPN).Name Validity Range (DR)");
        this.setPIDFieldValuePair("PID-6.10.1", "" ,"" ,"Mother's Maiden Name (XPN).Name Validity Range (DR).Range Start Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-6.10.2", "" ,"" ,"Mother's Maiden Name (XPN).Name Validity Range (DR).Range End Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-6.11", "" ,"" ,"Mother's Maiden Name (XPN).Name Assembly Order (ID)");
        this.setPIDFieldValuePair("PID-6.12", "" ,"" ,"Mother's Maiden Name (XPN).Effective Date (DTM)");
        this.setPIDFieldValuePair("PID-6.13", "" ,"" ,"Mother's Maiden Name (XPN).Expiration Date (DTM)");
        this.setPIDFieldValuePair("PID-6.14", "" ,"" ,"Mother's Maiden Name (XPN).Professional Suffix (ST)");
        this.setPIDFieldValuePair("PID-7", "0" ,"1" ,"Date/Time of Birth (DTM)");
        this.setPIDFieldValuePair("PID-8", "0" ,"1" ,"Administrative Sex (IS)");
        this.setPIDFieldValuePair("PID-9", "0" ,"*" ,"Patient Alias (XPN)");
        this.setPIDFieldValuePair("PID-9.1", "0" ,"*" ,"Patient Alias (XPN).Family Name (FN)");
        this.setPIDFieldValuePair("PID-9.1.1", "0" ,"*" ,"Patient Alias (XPN).Family Name (FN).Surname (ST)");
        this.setPIDFieldValuePair("PID-9.1.2", "" ,"" ,"Patient Alias (XPN).Family Name (FN).Own Surname Prefix (ST)");
        this.setPIDFieldValuePair("PID-9.1.3", "" ,"" ,"Patient Alias (XPN).Family Name (FN).Own Surname (ST)");
        this.setPIDFieldValuePair("PID-9.1.4", "" ,"" ,"Patient Alias (XPN).Family Name (FN).Surname Prefix from Partner/Spouse (ST)");
        this.setPIDFieldValuePair("PID-9.1.5", "" ,"" ,"Patient Alias (XPN).Family Name (FN).Surname from Partner/Spouse (ST)");
        this.setPIDFieldValuePair("PID-9.2", "" ,"" ,"Patient Alias (XPN).Given Name (ST)");
        this.setPIDFieldValuePair("PID-9.3", "" ,"" ,"Patient Alias (XPN).Second and Further Given Names or Initials Thereof (ST)");
        this.setPIDFieldValuePair("PID-9.4", "" ,"" ,"Patient Alias (XPN).Suffix (e.g., JR or III) (ST)");
        this.setPIDFieldValuePair("PID-9.5", "" ,"" ,"Patient Alias (XPN).Prefix (e.g., DR) (ST)");
        this.setPIDFieldValuePair("PID-9.6", "" ,"" ,"Patient Alias (XPN).Degree (e.g., MD) (IS)");
        this.setPIDFieldValuePair("PID-9.7", "" ,"" ,"Patient Alias (XPN).Name Type Code (ID)");
        this.setPIDFieldValuePair("PID-9.8", "" ,"" ,"Patient Alias (XPN).Name Representation Code (ID)");
        this.setPIDFieldValuePair("PID-9.9", "" ,"" ,"Patient Alias (XPN).Name Context (CWE)");
        this.setPIDFieldValuePair("PID-9.9.1", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-9.9.2", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-9.9.3", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-9.9.4", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-9.9.5", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-9.9.6", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-9.9.7", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-9.9.8", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-9.9.9", "" ,"" ,"Patient Alias (XPN).Name Context (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-9.10", "" ,"" ,"Patient Alias (XPN).Name Validity Range (DR)");
        this.setPIDFieldValuePair("PID-9.10.1", "" ,"" ,"Patient Alias (XPN).Name Validity Range (DR).Range Start Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-9.10.2", "" ,"" ,"Patient Alias (XPN).Name Validity Range (DR).Range End Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-9.11", "" ,"" ,"Patient Alias (XPN).Name Assembly Order (ID)");
        this.setPIDFieldValuePair("PID-9.12", "" ,"" ,"Patient Alias (XPN).Effective Date (DTM)");
        this.setPIDFieldValuePair("PID-9.13", "" ,"" ,"Patient Alias (XPN).Expiration Date (DTM)");
        this.setPIDFieldValuePair("PID-9.14", "" ,"" ,"Patient Alias (XPN).Professional Suffix (ST)");
        this.setPIDFieldValuePair("PID-10", "0" ,"*" ,"Race (CWE)");
        this.setPIDFieldValuePair("PID-10.1", "0" ,"*" ,"Race (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-10.2", "" ,"" ,"Race (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-10.3", "" ,"" ,"Race (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-10.4", "" ,"" ,"Race (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-10.5", "" ,"" ,"Race (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-10.6", "" ,"" ,"Race (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-10.7", "" ,"" ,"Race (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-10.8", "" ,"" ,"Race (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-10.9", "" ,"" ,"Race (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-11", "0" ,"*" ,"Patient Address (XAD)");
        this.setPIDFieldValuePair("PID-11.1", "0" ,"*" ,"Patient Address (XAD).Street Address (SAD)");
        this.setPIDFieldValuePair("PID-11.1.1", "0" ,"*" ,"Patient Address (XAD).Street Address (SAD).Street or Mailing Address (ST)");
        this.setPIDFieldValuePair("PID-11.1.2", "" ,"" ,"Patient Address (XAD).Street Address (SAD).Street Name (ST)");
        this.setPIDFieldValuePair("PID-11.1.3", "" ,"" ,"Patient Address (XAD).Street Address (SAD).Dwelling Number (ST)");
        this.setPIDFieldValuePair("PID-11.2", "" ,"" ,"Patient Address (XAD).Other Designation (ST)");
        this.setPIDFieldValuePair("PID-11.3", "" ,"" ,"Patient Address (XAD).City (ST)");
        this.setPIDFieldValuePair("PID-11.4", "" ,"" ,"Patient Address (XAD).State or Province (ST)");
        this.setPIDFieldValuePair("PID-11.5", "" ,"" ,"Patient Address (XAD).Zip or Postal Code (ST)");
        this.setPIDFieldValuePair("PID-11.6", "" ,"" ,"Patient Address (XAD).Country (ID)");
        this.setPIDFieldValuePair("PID-11.7", "" ,"" ,"Patient Address (XAD).Address Type (ID)");
        this.setPIDFieldValuePair("PID-11.8", "" ,"" ,"Patient Address (XAD).Other Geographic Designation (ST)");
        this.setPIDFieldValuePair("PID-11.9", "" ,"" ,"Patient Address (XAD).County/Parish Code (IS)");
        this.setPIDFieldValuePair("PID-11.10", "" ,"" ,"Patient Address (XAD).Census Tract (IS)");
        this.setPIDFieldValuePair("PID-11.11", "" ,"" ,"Patient Address (XAD).Address Representation Code (ID)");
        this.setPIDFieldValuePair("PID-11.12", "" ,"" ,"Patient Address (XAD).Address Validity Range (DR)");
        this.setPIDFieldValuePair("PID-11.12.1", "" ,"" ,"Patient Address (XAD).Address Validity Range (DR).Range Start Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-11.12.2", "" ,"" ,"Patient Address (XAD).Address Validity Range (DR).Range End Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-11.13", "" ,"" ,"Patient Address (XAD).Effective Date (DTM)");
        this.setPIDFieldValuePair("PID-11.14", "" ,"" ,"Patient Address (XAD).Expiration Date (DTM)");
        this.setPIDFieldValuePair("PID-11.15", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE)");
        this.setPIDFieldValuePair("PID-11.15.1", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-11.15.2", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-11.15.3", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-11.15.4", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-11.15.5", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-11.15.6", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-11.15.7", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-11.15.8", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-11.15.9", "" ,"" ,"Patient Address (XAD).Expiration Reason (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-11.16", "" ,"" ,"Patient Address (XAD).Temporary Indicator (ID)");
        this.setPIDFieldValuePair("PID-11.17", "" ,"" ,"Patient Address (XAD).Bad Address Indicator (ID)");
        this.setPIDFieldValuePair("PID-11.18", "" ,"" ,"Patient Address (XAD).Address Usage (ID)");
        this.setPIDFieldValuePair("PID-11.19", "" ,"" ,"Patient Address (XAD).Addressee (ST)");
        this.setPIDFieldValuePair("PID-11.20", "" ,"" ,"Patient Address (XAD).Comment (ST)");
        this.setPIDFieldValuePair("PID-11.21", "" ,"" ,"Patient Address (XAD).Preference Order (NM)");
        this.setPIDFieldValuePair("PID-11.22", "" ,"" ,"Patient Address (XAD).Protection Code (CWE)");
        this.setPIDFieldValuePair("PID-11.22.1", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-11.22.2", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-11.22.3", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-11.22.4", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-11.22.5", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-11.22.6", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-11.22.7", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-11.22.8", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-11.22.9", "" ,"" ,"Patient Address (XAD).Protection Code (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-11.23", "" ,"" ,"Patient Address (XAD).Address Identifier (EI)");
        this.setPIDFieldValuePair("PID-11.23.1", "" ,"" ,"Patient Address (XAD).Address Identifier (EI).Entity Identifier (ST)");
        this.setPIDFieldValuePair("PID-11.23.2", "" ,"" ,"Patient Address (XAD).Address Identifier (EI).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-11.23.3", "" ,"" ,"Patient Address (XAD).Address Identifier (EI).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-11.23.4", "" ,"" ,"Patient Address (XAD).Address Identifier (EI).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-12", "0" ,"1" ,"County Code (IS)");
        this.setPIDFieldValuePair("PID-13", "0" ,"*" ,"Phone Number - Home (XTN)");
        this.setPIDFieldValuePair("PID-13.1", "0" ,"*" ,"Phone Number - Home (XTN).Telephone Number (ST)");
        this.setPIDFieldValuePair("PID-13.2", "" ,"" ,"Phone Number - Home (XTN).Telecommunication Use Code (ID)");
        this.setPIDFieldValuePair("PID-13.3", "" ,"" ,"Phone Number - Home (XTN).Telecommunication Equipment Type (ID)");
        this.setPIDFieldValuePair("PID-13.4", "" ,"" ,"Phone Number - Home (XTN).Communication Address (ST)");
        this.setPIDFieldValuePair("PID-13.5", "" ,"" ,"Phone Number - Home (XTN).Country Code (NM)");
        this.setPIDFieldValuePair("PID-13.6", "" ,"" ,"Phone Number - Home (XTN).Area/City Code (NM)");
        this.setPIDFieldValuePair("PID-13.7", "" ,"" ,"Phone Number - Home (XTN).Local Number (NM)");
        this.setPIDFieldValuePair("PID-13.8", "" ,"" ,"Phone Number - Home (XTN).Extension (NM)");
        this.setPIDFieldValuePair("PID-13.9", "" ,"" ,"Phone Number - Home (XTN).Any Text (ST)");
        this.setPIDFieldValuePair("PID-13.10", "" ,"" ,"Phone Number - Home (XTN).Extension Prefix (ST)");
        this.setPIDFieldValuePair("PID-13.11", "" ,"" ,"Phone Number - Home (XTN).Speed Dial Code (ST)");
        this.setPIDFieldValuePair("PID-13.12", "" ,"" ,"Phone Number - Home (XTN).Unformatted Telephone number (ST)");
        this.setPIDFieldValuePair("PID-13.13", "" ,"" ,"Phone Number - Home (XTN).Effective Start Date (DTM)");
        this.setPIDFieldValuePair("PID-13.14", "" ,"" ,"Phone Number - Home (XTN).Expiration Date (DTM)");
        this.setPIDFieldValuePair("PID-13.15", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE)");
        this.setPIDFieldValuePair("PID-13.15.1", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-13.15.2", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-13.15.3", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-13.15.4", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-13.15.5", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-13.15.6", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-13.15.7", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-13.15.8", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-13.15.9", "" ,"" ,"Phone Number - Home (XTN).Expiration Reason (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-13.16", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE)");
        this.setPIDFieldValuePair("PID-13.16.1", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-13.16.2", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-13.16.3", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-13.16.4", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-13.16.5", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-13.16.6", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-13.16.7", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-13.16.8", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-13.16.9", "" ,"" ,"Phone Number - Home (XTN).Protection Code (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-13.17", "" ,"" ,"Phone Number - Home (XTN).Shared Telecommunication Identifier (EI)");
        this.setPIDFieldValuePair("PID-13.17.1", "" ,"" ,"Phone Number - Home (XTN).Shared Telecommunication Identifier (EI).Entity Identifier (ST)");
        this.setPIDFieldValuePair("PID-13.17.2", "" ,"" ,"Phone Number - Home (XTN).Shared Telecommunication Identifier (EI).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-13.17.3", "" ,"" ,"Phone Number - Home (XTN).Shared Telecommunication Identifier (EI).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-13.17.4", "" ,"" ,"Phone Number - Home (XTN).Shared Telecommunication Identifier (EI).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-13.18", "" ,"" ,"Phone Number - Home (XTN).Preference Order (NM)");
        this.setPIDFieldValuePair("PID-14", "0" ,"*" ,"Phone Number - Business (XTN)");
        this.setPIDFieldValuePair("PID-14.1", "0" ,"*" ,"Phone Number - Business (XTN).Telephone Number (ST)");
        this.setPIDFieldValuePair("PID-14.2", "" ,"" ,"Phone Number - Business (XTN).Telecommunication Use Code (ID)");
        this.setPIDFieldValuePair("PID-14.3", "" ,"" ,"Phone Number - Business (XTN).Telecommunication Equipment Type (ID)");
        this.setPIDFieldValuePair("PID-14.4", "" ,"" ,"Phone Number - Business (XTN).Communication Address (ST)");
        this.setPIDFieldValuePair("PID-14.5", "" ,"" ,"Phone Number - Business (XTN).Country Code (NM)");
        this.setPIDFieldValuePair("PID-14.6", "" ,"" ,"Phone Number - Business (XTN).Area/City Code (NM)");
        this.setPIDFieldValuePair("PID-14.7", "" ,"" ,"Phone Number - Business (XTN).Local Number (NM)");
        this.setPIDFieldValuePair("PID-14.8", "" ,"" ,"Phone Number - Business (XTN).Extension (NM)");
        this.setPIDFieldValuePair("PID-14.9", "" ,"" ,"Phone Number - Business (XTN).Any Text (ST)");
        this.setPIDFieldValuePair("PID-14.10", "" ,"" ,"Phone Number - Business (XTN).Extension Prefix (ST)");
        this.setPIDFieldValuePair("PID-14.11", "" ,"" ,"Phone Number - Business (XTN).Speed Dial Code (ST)");
        this.setPIDFieldValuePair("PID-14.12", "" ,"" ,"Phone Number - Business (XTN).Unformatted Telephone number (ST)");
        this.setPIDFieldValuePair("PID-14.13", "" ,"" ,"Phone Number - Business (XTN).Effective Start Date (DTM)");
        this.setPIDFieldValuePair("PID-14.14", "" ,"" ,"Phone Number - Business (XTN).Expiration Date (DTM)");
        this.setPIDFieldValuePair("PID-14.15", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE)");
        this.setPIDFieldValuePair("PID-14.15.1", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-14.15.2", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-14.15.3", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-14.15.4", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-14.15.5", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-14.15.6", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-14.15.7", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-14.15.8", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-14.15.9", "" ,"" ,"Phone Number - Business (XTN).Expiration Reason (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-14.16", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE)");
        this.setPIDFieldValuePair("PID-14.16.1", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-14.16.2", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-14.16.3", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-14.16.4", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-14.16.5", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-14.16.6", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-14.16.7", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-14.16.8", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-14.16.9", "" ,"" ,"Phone Number - Business (XTN).Protection Code (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-14.17", "" ,"" ,"Phone Number - Business (XTN).Shared Telecommunication Identifier (EI)");
        this.setPIDFieldValuePair("PID-14.17.1", "" ,"" ,"Phone Number - Business (XTN).Shared Telecommunication Identifier (EI).Entity Identifier (ST)");
        this.setPIDFieldValuePair("PID-14.17.2", "" ,"" ,"Phone Number - Business (XTN).Shared Telecommunication Identifier (EI).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-14.17.3", "" ,"" ,"Phone Number - Business (XTN).Shared Telecommunication Identifier (EI).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-14.17.4", "" ,"" ,"Phone Number - Business (XTN).Shared Telecommunication Identifier (EI).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-14.18", "" ,"" ,"Phone Number - Business (XTN).Preference Order (NM)");
        this.setPIDFieldValuePair("PID-15", "0" ,"1" ,"Primary Language (CWE)");
        this.setPIDFieldValuePair("PID-15.1", "0" ,"1" ,"Primary Language (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-15.2", "" ,"" ,"Primary Language (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-15.3", "" ,"" ,"Primary Language (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-15.4", "" ,"" ,"Primary Language (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-15.5", "" ,"" ,"Primary Language (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-15.6", "" ,"" ,"Primary Language (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-15.7", "" ,"" ,"Primary Language (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-15.8", "" ,"" ,"Primary Language (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-15.9", "" ,"" ,"Primary Language (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-16", "0" ,"1" ,"Marital Status (CWE)");
        this.setPIDFieldValuePair("PID-16.1", "0" ,"1" ,"Marital Status (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-16.2.1", "" ,"" ,"Marital Status (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-16.3.1", "" ,"" ,"Marital Status (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-16.4.1", "" ,"" ,"Marital Status (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-16.5.1", "" ,"" ,"Marital Status (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-16.6.1", "" ,"" ,"Marital Status (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-16.7.1", "" ,"" ,"Marital Status (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-16.8.1", "" ,"" ,"Marital Status (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-16.9.1", "" ,"" ,"Marital Status (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-17", "0" ,"1" ,"Religion (CWE)");
        this.setPIDFieldValuePair("PID-17.1", "0" ,"1" ,"Religion (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-17.2.1", "" ,"" ,"Religion (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-17.3.1", "" ,"" ,"Religion (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-17.4.1", "" ,"" ,"Religion (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-17.5.1", "" ,"" ,"Religion (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-17.6.1", "" ,"" ,"Religion (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-17.7.1", "" ,"" ,"Religion (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-17.8.1", "" ,"" ,"Religion (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-17.9.1", "" ,"" ,"Religion (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-18", "0" ,"1" ,"Patient Account Number (CX)");
        this.setPIDFieldValuePair("PID-18.1", "0" ,"1" ,"Patient Account Number (CX).ID Number (ST)");
        this.setPIDFieldValuePair("PID-18.2.1", "" ,"" ,"Patient Account Number (CX).Identifier Check Digit (ST)");
        this.setPIDFieldValuePair("PID-18.3.1", "" ,"" ,"Patient Account Number (CX).Check Digit Scheme (ID)");
        this.setPIDFieldValuePair("PID-18.4", "" ,"" ,"Patient Account Number (CX).Assigning Authority (HD)");
        this.setPIDFieldValuePair("PID-18.4.1", "" ,"" ,"Patient Account Number (CX).Assigning Authority (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-18.4.2", "" ,"" ,"Patient Account Number (CX).Assigning Authority (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-18.4.3", "" ,"" ,"Patient Account Number (CX).Assigning Authority (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-18.5.1", "" ,"" ,"Patient Account Number (CX).Identifier Type Code (ID)");
        this.setPIDFieldValuePair("PID-18.6", "" ,"" ,"Patient Account Number (CX).Assigning Facility (HD)");
        this.setPIDFieldValuePair("PID-18.6.1", "" ,"" ,"Patient Account Number (CX).Assigning Facility (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-18.6.2", "" ,"" ,"Patient Account Number (CX).Assigning Facility (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-18.6.3", "" ,"" ,"Patient Account Number (CX).Assigning Facility (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-18.7.1", "" ,"" ,"Patient Account Number (CX).Effective Date (DT)");
        this.setPIDFieldValuePair("PID-18.8.1", "" ,"" ,"Patient Account Number (CX).Expiration Date (DT)");
        this.setPIDFieldValuePair("PID-18.9", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE)");
        this.setPIDFieldValuePair("PID-18.9.1", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-18.9.2", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-18.9.3", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-18.9.4", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-18.9.5", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-18.9.6", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-18.9.7", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-18.9.8", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-18.9.9", "" ,"" ,"Patient Account Number (CX).Assigning Jurisdiction (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-18.10", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE)");
        this.setPIDFieldValuePair("PID-18.10.1", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-18.10.2", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-18.10.3", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-18.10.4", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-18.10.5", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-18.10.6", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-18.10.7", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-18.10.8", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-18.10.9", "" ,"" ,"Patient Account Number (CX).Assigning Agency or Department (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-19", "0" ,"1" ,"SSN Number - Patient (ST)");
        this.setPIDFieldValuePair("PID-20", "0" ,"1" ,"Driver's License Number - Patient (DLN)");
        this.setPIDFieldValuePair("PID-20.1", "0" ,"1" ,"Driver's License Number - Patient (DLN).License Number (ST)");
        this.setPIDFieldValuePair("PID-20.2.1", "" ,"" ,"Driver's License Number - Patient (DLN).Issuing State, Province, Country (IS)");
        this.setPIDFieldValuePair("PID-20.3.1", "" ,"" ,"Driver's License Number - Patient (DLN).Expiration Date (DT)");
        this.setPIDFieldValuePair("PID-21", "0" ,"*" ,"Mother's Identifier (CX)");
        this.setPIDFieldValuePair("PID-21.1", "0" ,"*" ,"Mother's Identifier (CX).ID Number (ST)");
        this.setPIDFieldValuePair("PID-21.2.1", "" ,"" ,"Mother's Identifier (CX).Identifier Check Digit (ST)");
        this.setPIDFieldValuePair("PID-21.3.1", "" ,"" ,"Mother's Identifier (CX).Check Digit Scheme (ID)");
        this.setPIDFieldValuePair("PID-21.4", "" ,"" ,"Mother's Identifier (CX).Assigning Authority (HD)");
        this.setPIDFieldValuePair("PID-21.4.1", "" ,"" ,"Mother's Identifier (CX).Assigning Authority (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-21.4.2", "" ,"" ,"Mother's Identifier (CX).Assigning Authority (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-21.4.3", "" ,"" ,"Mother's Identifier (CX).Assigning Authority (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-21.5.1", "" ,"" ,"Mother's Identifier (CX).Identifier Type Code (ID)");
        this.setPIDFieldValuePair("PID-21.6", "" ,"" ,"Mother's Identifier (CX).Assigning Facility (HD)");
        this.setPIDFieldValuePair("PID-21.6.1", "" ,"" ,"Mother's Identifier (CX).Assigning Facility (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-21.6.2", "" ,"" ,"Mother's Identifier (CX).Assigning Facility (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-21.6.3", "" ,"" ,"Mother's Identifier (CX).Assigning Facility (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-21.7.1", "" ,"" ,"Mother's Identifier (CX).Effective Date (DT)");
        this.setPIDFieldValuePair("PID-21.8.1", "" ,"" ,"Mother's Identifier (CX).Expiration Date (DT)");
        this.setPIDFieldValuePair("PID-21.9", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE)");
        this.setPIDFieldValuePair("PID-21.9.1", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-21.9.2", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-21.9.3", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-21.9.4", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-21.9.5", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-21.9.6", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-21.9.7", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-21.9.8", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-21.9.9", "" ,"" ,"Mother's Identifier (CX).Assigning Jurisdiction (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-21.10", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE)");
        this.setPIDFieldValuePair("PID-21.10.1", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-21.10.2", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-21.10.3", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-21.10.4", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-21.10.5", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-21.10.6", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-21.10.7", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-21.10.8", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-21.10.9", "" ,"" ,"Mother's Identifier (CX).Assigning Agency or Department (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-22", "0" ,"*" ,"Ethnic Group (CWE)");
        this.setPIDFieldValuePair("PID-22.1", "0" ,"*" ,"Ethnic Group (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-22.2.1", "" ,"" ,"Ethnic Group (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-22.3.1", "" ,"" ,"Ethnic Group (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-22.4.1", "" ,"" ,"Ethnic Group (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-22.5.1", "" ,"" ,"Ethnic Group (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-22.6.1", "" ,"" ,"Ethnic Group (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-22.7.1", "" ,"" ,"Ethnic Group (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-22.8.1", "" ,"" ,"Ethnic Group (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-22.9.1", "" ,"" ,"Ethnic Group (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-23", "0" ,"1" ,"Birth Place (ST)");
        this.setPIDFieldValuePair("PID-24", "0" ,"1" ,"Multiple Birth Indicator (ID)");
        this.setPIDFieldValuePair("PID-25", "0" ,"1" ,"Birth Order (NM)");
        this.setPIDFieldValuePair("PID-26", "0" ,"*" ,"Citizenship (CWE)");
        this.setPIDFieldValuePair("PID-26.1", "0" ,"*" ,"Citizenship (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-26.2.1", "" ,"" ,"Citizenship (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-26.3.1", "" ,"" ,"Citizenship (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-26.4.1", "" ,"" ,"Citizenship (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-26.5.1", "" ,"" ,"Citizenship (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-26.6.1", "" ,"" ,"Citizenship (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-26.7.1", "" ,"" ,"Citizenship (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-26.8.1", "" ,"" ,"Citizenship (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-26.9.1", "" ,"" ,"Citizenship (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-27", "0" ,"1" ,"Veterans Military Status (CWE)");
        this.setPIDFieldValuePair("PID-27.1", "0" ,"1" ,"Veterans Military Status (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-27.2.1", "" ,"" ,"Veterans Military Status (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-27.3.1", "" ,"" ,"Veterans Military Status (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-27.4.1", "" ,"" ,"Veterans Military Status (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-27.5.1", "" ,"" ,"Veterans Military Status (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-27.6.1", "" ,"" ,"Veterans Military Status (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-27.7.1", "" ,"" ,"Veterans Military Status (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-27.8.1", "" ,"" ,"Veterans Military Status (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-27.9.1", "" ,"" ,"Veterans Military Status (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-28", "0" ,"1" ,"Nationality (CWE)");
        this.setPIDFieldValuePair("PID-28.1", "0" ,"1" ,"Nationality (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-28.2.1", "" ,"" ,"Nationality (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-28.3.1", "" ,"" ,"Nationality (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-28.4.1", "" ,"" ,"Nationality (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-28.5.1", "" ,"" ,"Nationality (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-28.6.1", "" ,"" ,"Nationality (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-28.7.1", "" ,"" ,"Nationality (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-28.8.1", "" ,"" ,"Nationality (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-28.9.1", "" ,"" ,"Nationality (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-29", "0" ,"1" ,"Patient Death Date and Time (DTM)");
        this.setPIDFieldValuePair("PID-30", "0" ,"1" ,"Patient Death Indicator (ID)");
        this.setPIDFieldValuePair("PID-31", "0" ,"1" ,"Identity Unknown Indicator (ID)");
        this.setPIDFieldValuePair("PID-32", "0" ,"*" ,"Identity Reliability Code (IS)");
        this.setPIDFieldValuePair("PID-33", "0" ,"1" ,"Last Update Date/Time (DTM)");
        this.setPIDFieldValuePair("PID-34", "0" ,"1" ,"Last Update Facility (HD)");
        this.setPIDFieldValuePair("PID-34.1", "0" ,"1" ,"Last Update Facility (HD).Namespace ID (IS)");
        this.setPIDFieldValuePair("PID-34.2.1", "" ,"" ,"Last Update Facility (HD).Universal ID (ST)");
        this.setPIDFieldValuePair("PID-34.3.1", "" ,"" ,"Last Update Facility (HD).Universal ID Type (ID)");
        this.setPIDFieldValuePair("PID-35", "0" ,"1" ,"Species Code (CWE)");
        this.setPIDFieldValuePair("PID-35.1", "0" ,"1" ,"Species Code (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-35.2.1", "" ,"" ,"Species Code (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-35.3.1", "" ,"" ,"Species Code (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-35.4.1", "" ,"" ,"Species Code (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-35.5.1", "" ,"" ,"Species Code (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-35.6.1", "" ,"" ,"Species Code (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-35.7.1", "" ,"" ,"Species Code (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-35.8.1", "" ,"" ,"Species Code (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-35.9.1", "" ,"" ,"Species Code (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-36", "0" ,"1" ,"Breed Code (CWE)");
        this.setPIDFieldValuePair("PID-36.1", "0" ,"1" ,"Breed Code (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-36.2.1", "" ,"" ,"Breed Code (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-36.3.1", "" ,"" ,"Breed Code (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-36.4.1", "" ,"" ,"Breed Code (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-36.5.1", "" ,"" ,"Breed Code (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-36.6.1", "" ,"" ,"Breed Code (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-36.7.1", "" ,"" ,"Breed Code (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-36.8.1", "" ,"" ,"Breed Code (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-36.9.1", "" ,"" ,"Breed Code (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-37", "0" ,"1" ,"Strain (ST)");
        this.setPIDFieldValuePair("PID-38", "0" ,"*" ,"Production Class Code (CWE)");
        this.setPIDFieldValuePair("PID-38.1", "0" ,"*" ,"Production Class Code (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-38.2.1", "" ,"" ,"Production Class Code (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-38.3.1", "" ,"" ,"Production Class Code (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-38.4.1", "" ,"" ,"Production Class Code (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-38.5.1", "" ,"" ,"Production Class Code (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-38.6.1", "" ,"" ,"Production Class Code (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-38.7.1", "" ,"" ,"Production Class Code (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-38.8.1", "" ,"" ,"Production Class Code (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-38.9.1", "" ,"" ,"Production Class Code (CWE).Original Text (ST)");
        this.setPIDFieldValuePair("PID-39", "0" ,"*" ,"Tribal Citizenship (CWE)");
        this.setPIDFieldValuePair("PID-39.1", "0" ,"*" ,"Tribal Citizenship (CWE).Identifier (ST)");
        this.setPIDFieldValuePair("PID-39.2.1", "" ,"" ,"Tribal Citizenship (CWE).Text (ST)");
        this.setPIDFieldValuePair("PID-39.3.1", "" ,"" ,"Tribal Citizenship (CWE).Name of Coding System (ID)");
        this.setPIDFieldValuePair("PID-39.4.1", "" ,"" ,"Tribal Citizenship (CWE).Alternate Identifier (ST)");
        this.setPIDFieldValuePair("PID-39.5.1", "" ,"" ,"Tribal Citizenship (CWE).Alternate Text (ST)");
        this.setPIDFieldValuePair("PID-39.6.1", "" ,"" ,"Tribal Citizenship (CWE).Name of Alternate Coding System (ID)");
        this.setPIDFieldValuePair("PID-39.7.1", "" ,"" ,"Tribal Citizenship (CWE).Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-39.8.1", "" ,"" ,"Tribal Citizenship (CWE).Alternate Coding System Version ID (ST)");
        this.setPIDFieldValuePair("PID-39.9.1", "" ,"" ,"Tribal Citizenship (CWE).Original Text (ST)");
    }
    
    public void buildPV1Segement(){
    }
    
    public void buildMasterForAllSegement(){
//        this.setAllSegmentMaster("MSH-1", "segment_ID");
        this.setAllSegmentMaster("MSH-2", "MSH-2-encoding_characters");
        this.setAllSegmentMaster("MSH-3", "MSH-3-sending_application");
        this.setAllSegmentMaster("MSH-3.1", "MSH-3-sending_application.namespace_ID");
        this.setAllSegmentMaster("MSH-3.2", "MSH-3-sending_application.universal_ID");
        this.setAllSegmentMaster("MSH-3.3", "MSH-3-sending_application.universal_ID_type");
        this.setAllSegmentMaster("MSH-4", "MSH-4-sending_facility");
        this.setAllSegmentMaster("MSH-4.1", "MSH-4-sending_facility.namespace_ID");
        this.setAllSegmentMaster("MSH-4.2", "MSH-4-sending_facility.universal_ID");
        this.setAllSegmentMaster("MSH-4.3", "MSH-4-sending_facility.universal_ID_type");
        this.setAllSegmentMaster("MSH-5", "MSH-5-receiving_application");
        this.setAllSegmentMaster("MSH-5.1", "MSH-5-receiving_application.namespace_ID");
        this.setAllSegmentMaster("MSH-5.2", "MSH-5-receiving_application.universal_ID");
        this.setAllSegmentMaster("MSH-5.3", "MSH-5-receiving_application.universal_ID_type");
        this.setAllSegmentMaster("MSH-6", "MSH-6-receiving_facility");
        this.setAllSegmentMaster("MSH-6.1", "MSH-6-receiving_facility.namespace_ID");
        this.setAllSegmentMaster("MSH-6.2", "MSH-6-receiving_facility.universal_ID");
        this.setAllSegmentMaster("MSH-6.3", "MSH-6-receiving_facility.universal_ID_type");
        this.setAllSegmentMaster("MSH-7", "MSH-7-message_date/time");
        this.setAllSegmentMaster("MSH-8", "MSH-8-security");
        this.setAllSegmentMaster("MSH-9", "MSH-9-message_type");
        this.setAllSegmentMaster("MSH-9.1", "MSH-9-message_type.MSH-9-1_message_type");
        this.setAllSegmentMaster("MSH-9.2", "MSH-9-message_type.MSH-9-2_trigger_event");
        this.setAllSegmentMaster("MSH-10", "MSH-10-message_control_ID");
        this.setAllSegmentMaster("MSH-11", "MSH-11-processing_ID");
        this.setAllSegmentMaster("MSH-11.1", "MSH-11-processing_ID.processing_ID");
        this.setAllSegmentMaster("MSH-11.2", "MSH-11-processing_ID.processing_mode");
        this.setAllSegmentMaster("MSH-12", "MSH-12-version_ID");
        this.setAllSegmentMaster("MSH-13", "MSH-13-sequence_number");
        this.setAllSegmentMaster("MSH-14", "MSH-14-continuation_pointer");
        this.setAllSegmentMaster("MSH-15", "MSH-15-accept_ack_type");
        this.setAllSegmentMaster("MSH-16", "MSH-16-application_ack_type");
        this.setAllSegmentMaster("MSH-17", "MSH-17-country_code");
        this.setAllSegmentMaster("MSH-18", "MSH-18_character_set");
        this.setAllSegmentMaster("MSH-19", "MSH-19_principal_language");
        this.setAllSegmentMaster("MSH-19.1", "MSH-19_principal_language.ID_code");
        this.setAllSegmentMaster("MSH-19.2", "MSH-19_principal_language.text");
        this.setAllSegmentMaster("MSH-19.3", "MSH-19_principal_language.coding_scheme");
        this.setAllSegmentMaster("MSH-19.4", "MSH-19_principal_language.alternate_ID");
        this.setAllSegmentMaster("MSH-19.5", "MSH-19_principal_language.alternate_text");
        this.setAllSegmentMaster("MSH-19.6", "MSH-19_principal_language.alternate_coding_scheme");
        this.setAllSegmentMaster("PID-1", "PID-1-set_ID");
        this.setAllSegmentMaster("PID-2", "PID-2-patient_ID_external");
        this.setAllSegmentMaster("PID-2.1", "PID-2-patient_ID_external.ID_number");
        this.setAllSegmentMaster("PID-2.2", "PID-2-patient_ID_external.check_digit");
        this.setAllSegmentMaster("PID-2.3", "PID-2-patient_ID_external.check_digit_scheme");
        this.setAllSegmentMaster("PID-2.4", "PID-2-patient_ID_external.assigning_authority");
        this.setAllSegmentMaster("PID-2.4.1", "PID-2-patient_ID_external.assigning_authority.namespace_ID");
        this.setAllSegmentMaster("PID-2.4.2", "PID-2-patient_ID_external.assigning_authority.universal_ID");
        this.setAllSegmentMaster("PID-2.4.3", "PID-2-patient_ID_external.assigning_authority.universal_ID_type");
        this.setAllSegmentMaster("PID-2.5", "PID-2-patient_ID_external.ID_type_code");
        this.setAllSegmentMaster("PID-2.6", "PID-2-patient_ID_external.assigning_fac");
        this.setAllSegmentMaster("PID-2.6.1", "PID-2-patient_ID_external.assigning_fac.namespace_ID");
        this.setAllSegmentMaster("PID-2.6.2", "PID-2-patient_ID_external.assigning_fac.universal_ID");
        this.setAllSegmentMaster("PID-2.6.3", "PID-2-patient_ID_external.assigning_fac.universal_ID_type");
        this.setAllSegmentMaster("PID-3", "PID-3-patient_ID_internal");
        this.setAllSegmentMaster("PID-3.1", "PID-3-patient_ID_internal.ID_number");
        this.setAllSegmentMaster("PID-3.2", "PID-3-patient_ID_internal.check_digit");
        this.setAllSegmentMaster("PID-3.3", "PID-3-patient_ID_internal.check_digit_scheme");
        this.setAllSegmentMaster("PID-3.4", "PID-3-patient_ID_internal.assigning_authority");
        this.setAllSegmentMaster("PID-3.4.1", "PID-3-patient_ID_internal.assigning_authority.namespace_ID");
        this.setAllSegmentMaster("PID-3.4.2", "PID-3-patient_ID_internal.assigning_authority.universal_ID");
        this.setAllSegmentMaster("PID-3.4.3", "PID-3-patient_ID_internal.assigning_authority.universal_ID_type");
        this.setAllSegmentMaster("PID-3.5", "PID-3-patient_ID_internal.ID_type_code");
        this.setAllSegmentMaster("PID-3.6", "PID-3-patient_ID_internal.assigning_fac");
        this.setAllSegmentMaster("PID-3.6.1", "PID-3-patient_ID_internal.assigning_fac.namespace_ID");
        this.setAllSegmentMaster("PID-3.6.2", "PID-3-patient_ID_internal.assigning_fac.universal_ID");
        this.setAllSegmentMaster("PID-3.6.3", "PID-3-patient_ID_internal.assigning_fac.universal_ID_type");
        this.setAllSegmentMaster("PID-4", "PID-4-alternate_patient_ID");
        this.setAllSegmentMaster("PID-4.1", "PID-4-alternate_patient_ID.ID_number");
        this.setAllSegmentMaster("PID-4.2", "PID-4-alternate_patient_ID.check_digit");
        this.setAllSegmentMaster("PID-4.3", "PID-4-patient_ID_internal.check_digit_scheme");
        this.setAllSegmentMaster("PID-4.4", "PID-4-patient_ID_internal.assigning_authority");
        this.setAllSegmentMaster("PID-4.4.1", "PID-4-patient_ID_internal.assigning_authority.namespace_ID");
        this.setAllSegmentMaster("PID-4.4.2", "PID-4-patient_ID_internal.assigning_authority.universal_ID");
        this.setAllSegmentMaster("PID-4.4.3", "PID-4-patient_ID_internal.assigning_authority.universal_ID_type");
        this.setAllSegmentMaster("PID-4.5", "PID-4-patient_ID_internal.ID_type_code");
        this.setAllSegmentMaster("PID-4.6", "PID-4-patient_ID_internal.assigning_fac");
        this.setAllSegmentMaster("PID-4.6.1", "PID-4-patient_ID_internal.assigning_fac.namespace_ID");
        this.setAllSegmentMaster("PID-4.6.2", "PID-4-patient_ID_internal.assigning_fac.universal_ID");
        this.setAllSegmentMaster("PID-4.6.3", "PID-4-patient_ID_internal.assigning_fac.universal_ID_type");
        this.setAllSegmentMaster("PID-5", "PID-5-patient_name");
        this.setAllSegmentMaster("PID-5.1", "PID-5-patient_name.last_name");
        this.setAllSegmentMaster("PID-5.2", "PID-5-patient_name.first_name");
        this.setAllSegmentMaster("PID-5.3", "PID-5-patient_name.middle_initial_or_name");
        this.setAllSegmentMaster("PID-5.4", "PID-5-patient_name.suffix");
        this.setAllSegmentMaster("PID-5.5", "PID-5-patient_name.prefix");
        this.setAllSegmentMaster("PID-5.6", "PID-5-patient_name.degree");
        this.setAllSegmentMaster("PID-5.7", "PID-5-patient_name.name_type");
        this.setAllSegmentMaster("PID-5.8", "PID-5-patient_name.name_representation");
        this.setAllSegmentMaster("PID-6", "PID-6-mothers_maiden_name");
        this.setAllSegmentMaster("PID-6.1", "PID-6-mothers_maiden_name.last_name");
        this.setAllSegmentMaster("PID-6.2", "PID-6-mothers_maiden_name.first_name");
        this.setAllSegmentMaster("PID-6.3", "PID-6-mothers_maiden_name.middle_initial_or_name");
        this.setAllSegmentMaster("PID-6.4", "PID-6-mothers_maiden_name.suffix");
        this.setAllSegmentMaster("PID-6.5", "PID-6-mothers_maiden_name.prefix");
        this.setAllSegmentMaster("PID-6.6", "PID-6-mothers_maiden_name.degree");
        this.setAllSegmentMaster("PID-6.7", "PID-6-mothers_maiden_name.name_type");
        this.setAllSegmentMaster("PID-6.8", "PID-6-mothers_maiden_name.name_representation");
        this.setAllSegmentMaster("PID-7", "PID-7-date_of_birth");
        this.setAllSegmentMaster("PID-8", "PID-8-sex");
        this.setAllSegmentMaster("PID-9", "PID-9-patient_alias");
        this.setAllSegmentMaster("PID-9.1", "PID-9-patient_alias.last_name");
        this.setAllSegmentMaster("PID-9.2", "PID-9-patient_alias.first_name");
        this.setAllSegmentMaster("PID-9.3", "PID-9-patient_alias.middle_initial_or_name");
        this.setAllSegmentMaster("PID-9.4", "PID-9-patient_alias.suffix");
        this.setAllSegmentMaster("PID-9.5", "PID-9-patient_alias.prefix");
        this.setAllSegmentMaster("PID-9.6", "PID-9-patient_alias.degree");
        this.setAllSegmentMaster("PID-9.7", "PID-9-patient_alias.name_type");
        this.setAllSegmentMaster("PID-9.8", "PID-9-patient_alias.name_representation");
        this.setAllSegmentMaster("PID-10", "PID-10-race");
        this.setAllSegmentMaster("PID-11", "PID-11-patient_address");
        this.setAllSegmentMaster("PID-11.1", "PID-11-patient_address.street_1");
        this.setAllSegmentMaster("PID-11.2", "PID-11-patient_address.street_2");
        this.setAllSegmentMaster("PID-11.3", "PID-11-patient_address.city");
        this.setAllSegmentMaster("PID-11.4", "PID-11-patient_address.state_or_province");
        this.setAllSegmentMaster("PID-11.5", "PID-11-patient_address.zip");
        this.setAllSegmentMaster("PID-11.6", "PID-11-patient_address.country");
        this.setAllSegmentMaster("PID-11.7", "PID-11-patient_address.type");
        this.setAllSegmentMaster("PID-11.8", "PID-11-patient_address.geographic_designation");
        this.setAllSegmentMaster("PID-11.9", "PID-11-patient_address.county/parish");
        this.setAllSegmentMaster("PID-11.10", "PID-11-patient_address.census_tract");
        this.setAllSegmentMaster("PID-12", "PID-12-county_code");
        this.setAllSegmentMaster("PID-13", "PID-13-home_phone");
        this.setAllSegmentMaster("PID-13.1", "PID-13-home_phone.telephone_number");
        this.setAllSegmentMaster("PID-13.2", "PID-13-home_phone.telecom_use");
        this.setAllSegmentMaster("PID-13.3", "PID-13-home_phone.telecom_equip_type");
        this.setAllSegmentMaster("PID-13.4", "PID-13-home_phone.email_address");
        this.setAllSegmentMaster("PID-13.5", "PID-13-home_phone.country_code");
        this.setAllSegmentMaster("PID-13.6", "PID-13-home_phone.area_code");
        this.setAllSegmentMaster("PID-13.7", "PID-13-home_phone.phone_number");
        this.setAllSegmentMaster("PID-13.8", "PID-13-home_phone.extension");
        this.setAllSegmentMaster("PID-13.9", "PID-13-home_phone.comment");
        this.setAllSegmentMaster("PID-14", "PID-14-business-phone");
        this.setAllSegmentMaster("PID-14.1", "PID-14-business-phone.telephone_number");
        this.setAllSegmentMaster("PID-14.2", "PID-14-business-phone.telecom_use");
        this.setAllSegmentMaster("PID-14.3", "PID-14-business-phone.telecom_equip_type");
        this.setAllSegmentMaster("PID-14.4", "PID-14-business-phone.email_address");
        this.setAllSegmentMaster("PID-14.5", "PID-14-business-phone.country_code");
        this.setAllSegmentMaster("PID-14.6", "PID-14-business-phone.area_code");
        this.setAllSegmentMaster("PID-14.7", "PID-14-business-phone.phone_number");
        this.setAllSegmentMaster("PID-14.8", "PID-14-business-phone.extension");
        this.setAllSegmentMaster("PID-14.9", "PID-14-business-phone.comment");
        this.setAllSegmentMaster("PID-15", "PID-15-language");
        this.setAllSegmentMaster("PID-15.1", "PID-15-language.ID_code");
        this.setAllSegmentMaster("PID-15.2", "PID-15-language.text");
        this.setAllSegmentMaster("PID-15.3", "PID-15-language.coding_scheme");
        this.setAllSegmentMaster("PID-15.4", "PID-15-language.alternate_ID");
        this.setAllSegmentMaster("PID-15.5", "PID-15-language.alternate_text");
        this.setAllSegmentMaster("PID-15.6", "PID-15-language.alternate_coding_scheme");
        this.setAllSegmentMaster("PID-16", "PID-16-marital_status");
        this.setAllSegmentMaster("PID-17", "PID-17-religion");
        this.setAllSegmentMaster("PID-18", "PID-18-account_number");
        this.setAllSegmentMaster("PID-18.1", "PID-18-account_number.ID_number");
        this.setAllSegmentMaster("PID-18.2", "PID-18-account_number.check_digit");
        this.setAllSegmentMaster("PID-18.3", "PID-18-account_number.check_digit_scheme");
        this.setAllSegmentMaster("PID-18.4", "PID-18-account_number.assigning_authority");
        this.setAllSegmentMaster("PID-18.4.1", "PID-18-account_number.assigning_authority.namespace_ID");
        this.setAllSegmentMaster("PID-18.4.2", "PID-18-account_number.assigning_authority.universal_ID");
        this.setAllSegmentMaster("PID-18.4.3", "PID-18-account_number.assigning_authority.universal_ID_type");
        this.setAllSegmentMaster("PID-18.5", "PID-18-account_number.ID_type_code");
        this.setAllSegmentMaster("PID-18.6", "PID-18-account_number.assigning_fac");
        this.setAllSegmentMaster("PID-18.6.1", "PID-18-account_number.assigning_fac.namespace_ID");
        this.setAllSegmentMaster("PID-18.6.2", "PID-18-account_number.assigning_fac.universal_ID");
        this.setAllSegmentMaster("PID-18.6.3", "PID-18-account_number.assigning_fac.universal_ID_type");
        this.setAllSegmentMaster("PID-19", "PID-19-SSN_number");
        this.setAllSegmentMaster("PID-20", "PID-20-driver_lic_num");
        this.setAllSegmentMaster("PID-20.1", "PID-20-driver_lic_num.drivers_lic_num");
        this.setAllSegmentMaster("PID-20.2", "PID-20-driver_lic_num.issuing_state");
        this.setAllSegmentMaster("PID-20.3", "PID-20-driver_lic_num.expiration_date");
        this.setAllSegmentMaster("PID-21", "PID-21-mothers_ID");
        this.setAllSegmentMaster("PID-21.1", "PID-21-mothers_ID.ID_number");
        this.setAllSegmentMaster("PID-21.2", "PID-21-mothers_ID.check_digit");
        this.setAllSegmentMaster("PID-21.3", "PID-21-mothers_ID.check_digit_scheme");
        this.setAllSegmentMaster("PID-21.4", "PID-21-mothers_ID.assigning_authority");
        this.setAllSegmentMaster("PID-21.4.1", "PID-21-mothers_ID.assigning_authority.namespace_ID");
        this.setAllSegmentMaster("PID-21.4.2", "PID-21-mothers_ID.assigning_authority.universal_ID");
        this.setAllSegmentMaster("PID-21.4.3", "PID-21-mothers_ID.assigning_authority.universal_ID_type");
        this.setAllSegmentMaster("PID-21.5", "PID-21-mothers_ID.ID_type_code");
        this.setAllSegmentMaster("PID-21.6", "PID-21-mothers_ID.assigning_fac");
        this.setAllSegmentMaster("PID-21.6.1", "PID-21-mothers_ID.assigning_fac.namespace_ID");
        this.setAllSegmentMaster("PID-21.6.2", "PID-21-mothers_ID.assigning_fac.universal_ID");
        this.setAllSegmentMaster("PID-21.6.3", "PID-21-mothers_ID.assigning_fac.universal_ID_type");
        this.setAllSegmentMaster("PID-22", "PID-22-ethnic_group");
        this.setAllSegmentMaster("PID-23", "PID-23-birth_place");
        this.setAllSegmentMaster("PID-24", "PID-24-multiple_birth_indicator");
        this.setAllSegmentMaster("PID-25", "PID-25-birth_order");
        this.setAllSegmentMaster("PID-26", "PID-26-citizenship");
        this.setAllSegmentMaster("PID-27", "PID-27-veterans_military_status");
        this.setAllSegmentMaster("PID-27.1", "PID-27-veterans_military_status.ID_code");
        this.setAllSegmentMaster("PID-27.2", "PID-27-veterans_military_status.text");
        this.setAllSegmentMaster("PID-27.3", "PID-27-veterans_military_status.coding_scheme");
        this.setAllSegmentMaster("PID-27.4", "PID-27-veterans_military_status.alternate_ID");
        this.setAllSegmentMaster("PID-27.5", "PID-27-veterans_military_status.alternate_text");
        this.setAllSegmentMaster("PID-27.6", "PID-27-veterans_military_status.alternate_coding_scheme");
        this.setAllSegmentMaster("PID-28", "PID-28-nationality");
        this.setAllSegmentMaster("PID-29", "PID-29-patient_death_date-time");
        this.setAllSegmentMaster("PID-30", "PID-30-patient_death_indicator");
    }
    
    public String getStandardTemplateName(String treFieldName){
        String result = "";
        if(this.getAllSegmentMaster().get(treFieldName) != null){
            result = this.getAllSegmentMaster().get(treFieldName).toString();
        }
        return result;
    }
    
}
